// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdz0EqaQcCAy1qPkULkq5RsRYmsOCJz0A',
    appId: '1:176265089519:web:ef9c35ce17e9f8135d661a',
    messagingSenderId: '176265089519',
    projectId: 'rumini-5f6ff',
    authDomain: 'rumini-5f6ff.firebaseapp.com',
    storageBucket: 'rumini-5f6ff.firebasestorage.app',
    measurementId: 'G-WSV5RCWZYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbDymQmM-tJlpVA1wCVtrndXR2dzxmmnc',
    appId: '1:176265089519:android:629d90d78d4661a75d661a',
    messagingSenderId: '176265089519',
    projectId: 'rumini-5f6ff',
    storageBucket: 'rumini-5f6ff.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdz0EqaQcCAy1qPkULkq5RsRYmsOCJz0A',
    appId: '1:176265089519:web:8965f12dda38effd5d661a',
    messagingSenderId: '176265089519',
    projectId: 'rumini-5f6ff',
    authDomain: 'rumini-5f6ff.firebaseapp.com',
    storageBucket: 'rumini-5f6ff.firebasestorage.app',
    measurementId: 'G-TX1HSHGXGV',
  );

}